server:
  servlet:
    context-path: /dscross
  port: 8085

spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: druid,sharding,custom

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: cn.xzxy.lewy.dscross.pojo
  configLocation: classpath:mybatis/mybatis-config.xml

#showSql
logging:
  level:
    cn:
      xzxy:
        lewy:
          dscross:
            mapper: debug