#数据库驱动包类路径
dataBaseDriver:
  driver1: oracle.jdbc.driver.OracleDriver
  driver2: com.microsoft.sqlserver.jdbc.SQLServerDriver
  driver3: com.mysql.cj.jdbc.Driver
  driver4: org.apache.hive.jdbc.HiveDriver

#数据库测试sql，编号对应上面的数据库驱动
db-test-sql:
  sql1: select 1 from dual
  sql2: select 1
  sql3: select 1
  sql4: select 1

#数据库获取表sql，编号对应上面的数据库驱动
db-tables-sql:
  sql1: SELECT TABLE_NAME, COMMENTS TABLE_COMMENT FROM USER_TAB_COMMENTS WHERE TABLE_TYPE='TABLE' ORDER BY TABLE_NAME
  sql2: SELECT NAME AS TABLE_NAME FROM SYSOBJECTS WHERE XTYPE='U' ORDER BY NAME
  sql3: SELECT TABLE_NAME, TABLE_COMMENT FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='%s'
  sql4: select t.TBL_NAME as TABLE_NAME from DBS b, TBLS t where b.`NAME` = '%s' and b.DB_ID = t.DB_ID

#数据库获取字段sql，编号对应上面的数据库驱动
db-fileds-sql:
  sql1: SELECT A.COLUMN_NAME,A.DATA_TYPE,A.DATA_LENGTH,B.COMMENTS,0 IS_PRIMARY, 0 IS_ENCRYPT, 0 IS_CRITERIA FROM USER_TAB_COLUMNS A, USER_COL_COMMENTS B WHERE A.TABLE_NAME = B.TABLE_NAME AND A.COLUMN_NAME = B.COLUMN_NAME AND A.TABLE_NAME= '%s' ORDER BY A.COLUMN_NAME
  sql2: SELECT COLUMN_NAME,DATA_TYPE,CHARACTER_MAXIMUM_LENGTH AS DATA_LENGTH,COLUMN_DEFAULT AS COMMENTS,0 IS_PRIMARY,0 IS_ENCRYPT,0 IS_CRITERIA from information_schema.columns WHERE table_name = '%S'
  sql3: SELECT COLUMN_NAME,DATA_TYPE,CHARACTER_MAXIMUM_LENGTH AS DATA_LENGTH,COLUMN_COMMENT COMMENTS,0 IS_PRIMARY,0 IS_ENCRYPT,0 IS_CRITERIA from information_schema.COLUMNS WHERE table_name = '%S' AND TABLE_SCHEMA='%s'
  sql4: select COLUMN_NAME, `COMMENT` as COMMENTS, TYPE_NAME as DATA_TYPE, '' as DATA_LENGTH, 0 IS_PRIMARY, 0 IS_ENCRYPT, 0 IS_CRITERIA from COLUMNS_V2 where CD_ID = (select CD_ID from SDS where SD_ID = (select SD_ID from DBS b, TBLS t where b.`NAME` = 'dbName' and b.DB_ID = t.DB_ID and t.TBL_NAME = 'tbName')) order by INTEGER_IDX

datasource-cross:
  prestoName: undefined